services:
  app:
    image: ghcr.io/loftwah/linkarooie:latest
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./storage:/rails/storage
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  sidekiq:
    image: ghcr.io/loftwah/linkarooie:latest
    command: bundle exec sidekiq
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./storage:/rails/storage
    depends_on:
      - redis

volumes:
  redis_data: