# config/sidekiq_scheduler.yml
aggregate_metrics:
  cron: '0 1 * * *'  # Run at 1 AM every day
  class: AggregateMetricsJob

backup_database:
  cron: '0 2 * * *'  # Runs daily at 2 AM
  class: BackupDatabaseJob

cleanup_old_backups:
  cron: '0 3 * * *'  # Runs daily at 3 AM (after backup job)
  class: CleanupOldBackupsJob