name: CI

on:
  pull_request:
    branches:
      - dl/kamal-2-test
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      SPACES_BUCKET_CONTENT: ${{ secrets.SPACES_BUCKET_CONTENT }} # Use the secret for bucket content
      SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }} # Add secret for Spaces access key
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }} # Add secret for Spaces secret access key
      SPACES_REGION: ${{ secrets.SPACES_REGION }} # Add secret for region (e.g., syd1)
      AWS_REGION: 'ap-southeast-2' # Dummy value for occasional failing tests              
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          npm install

      - name: Build Vite assets
        run: bundle exec rake vite:build

      - name: Compile Tailwind CSS
        run: bundle exec rails tailwindcss:build

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rails db:seed

      - name: Run tests
        run: bundle exec rspec

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image locally for testing
      - name: Build Docker image
        run: |
          docker build -t myapp:ci-test .
