name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        run: bundle exec rails db:create db:migrate
        env:
          RAILS_ENV: test

      - name: Run tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
