name: Rollback

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to rollback'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Deploy rollback to droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        script: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Stop the running containers
          docker compose -f docker-compose.prod.yml down
          
          # Pull the specific release tag
          docker compose -f docker-compose.prod.yml pull ghcr.io/loftwah/linkarooie:${{ github.event.inputs.tag }}
          
          # Start the rolled-back version of the containers
          docker compose -f docker-compose.prod.yml up -d
          
          # Remove unused images and containers
          docker system prune -af
